### DISCUSSION TITLE
Should we allow both strings and object representations of input data in places?

### DISCUSSION THREAD

**Discussion by bdarcus** [bdarcus/csl-next-attic#14] [Q&A]
_I don't think this is a first order question; more for latter, if this project goes anywhere. But just to record it ..._

Hayagriva has an interesting [new YAML format](https://github.com/typst/hayagriva/blob/main/docs/file-format.md)  (which seems well-designed) that allows either strings or structured representations in key places, much as we've done in CSL 1.1 work for titles and dates.

```yaml
publisher: UN World Food Programme
```

vs.

```yaml
publisher:
    value: imagiNary Publishing
    title-case: Imaginary Publishing
    sentence-case: imagiNary publishing
```

We're obviously all struggling with the concision vs correctness issue, so maybe we can allow both?

_Originally posted by @bdarcus in https://github.com/bdarcus/csl-next/issues/12#issuecomment-1486669557_
