### DISCUSSION TITLE
Is a template language like liquidir mustache with YAML any kind of realistic possibility?

### DISCUSSION THREAD

**Discussion by bdarcus** [bdarcus/csl-next-attic#21] [Q&A] [answered]
My initial idea was to consider the possibility of throwing out XML entirely.

But as I started to think about it, that didn't seem practical.

I'm still not convinced it is possible, or a good idea, but Just looking at this again, it might work something like this, with a similar flatter possibility in XML.

The idea here is to use piped filters to do what we've typically done with a lot of XML: transform input data into output strings.

Here's a partial reference item template in liquid:

```liquid
{%
  ###############################################
  # Use piped filtes to transform author lists
  ###############################################
%}
{{ item.author | shorten: "3 1" | etal }} 
{%
  ###############################################
  # Again, piped filters, but here the 
  # second wraps the content if present.
  # The date is a default filter, with the arg.
  ###############################################
%}
{{ item.issued | date: "%Y"  | parenwrap }}
{{ item.title | titlecase  | italicize }}
```

So for liquid, there's a [standard set of filters](https://shopify.github.io/liquid/filters/abs/) that's pretty extensive. A possible future CSL could simply add domain-specific ones (in the example above, all but `date`).

Aside: I thought that `parenwrap` example was clever, though it may not work, since we'd need to be able to insert arbitrary text, terms, etc within the wrapper. Maybe that's possible with filters; don't know.

Anyway, integrated into yaml:

```yaml
citation:
  default: '{{ item.author | shorten: "3 1" | etal }} ...'
```

Such templates probably wouldn't be needed for citations or bibliographies. Grouping and sorting and such could probably be configured in native YAML (or XML attribute) structures.

```yaml
citation:
  group-by: cs-author-year
  sort: cs-author-year
```

And XML (though there's no way to attach arguments to these hypothetical filters):

```xml
<list group-by="cs-author-year" sort="cs-author-year">
  <reference variable="author" transforms="cs-shorten-apa cs-etal"/>
```

This was basically my original "crazy" idea @denismaier .

It does have some advantages, but no doubt some disadvantages. In the XML example, there's no real reason not to use the kind of attributes for a lot that which we already have.

In the end, the idea of filters or transforms, and a possible non-XML template language, still seems like it may have promise.

**Comment by bdarcus** [comment, marked as answer]
Possible? Yes.

Worth it? Hard to know; that's really up to CSL developers, etc, since they would need to implement it.

**Reply by denismaier** [reply]
I must admit I'm not sure if I really like this template syntax. At least, things like item should be implicit to make it more concise. Also, could we do without the double braces?

```
citation
  author | shorten: "3 1" | etal
  issued | date: "%Y"
  locator | range-format chicago
end
```

But that'd be a completely new language...

**Reply by bdarcus** [reply]
Right.

 I think that kind of syntax is to enable to integrate it into surrounding content.

In citar, we have this simple template language, for another example:

```
Notes on ${author editor}, ${title}.
```

**Reply by bdarcus** [reply]
I actually like your hypothetical example @denismaier. A "completely new language" may be justified if it's simple enough?

How would you deal with substitution, affixes, and formatting?

I was just playing with this, before having looked at your's again:

```yaml
---
title: APA CSL style
templates:
  cs-author-apa: ( author | editor )>cs-short-apa
  cs-issued-year-apa: issued>year>addsuffix
citation:
  group-by: cs-author-year
  sort: cs-author-year
  templates:
    default: ${ "(" ${ cs-author-apa ", "} ${ cs-issued-year-apa } ")" }
    narrative:  ${ cs-author-apa ", "} ${ "(" ${ cs-issued-year-apa } ")" }
```

So braces are groups, parens with `|` are substitutions, and `>` is one-or-more filters.

In this idea, filters would also handle formatting (italics and such).

A commit with example schema and minimal style:

https://github.com/bdarcus/csl-next/commit/41517a55918664cfb28238c75b9dd55f320644ab

On template languages, there are different approaches to the syntax:

https://www.creativebloq.com/web-design/templating-engines-9134396

Some look more like programming languages, probably not so user-friendly, but more flexible.

Most use things like double-braces to define executable pieces.

BTW, I was just taking a look at a commercial reference manager's template language. That is a flat template, without any groups or substitution logic that I can see, and which uses some special characters to link, de-link, etc adjacent content.

A flat variant, without groups/brackets:

```yaml
  templates:
    default: '(cs-author-apa, cs_issued-year-apa)'
    narrative: 'cs-author-apa, (cs_issued-year-apa)'
```

But then this is totally valid YAML, without need to parse a string ...

```yaml
    default: [ "(", t: cs-author-apa, ", ", t: cs-issued-year-apa, ":", t: cs-locators, ")"]
```

... that is just this:

```yaml
default:
  - (
  - t: cs-author-apa
  - ", "
  - t: cs-issued-year-apa
  - ":"
  - t: cs-locators
  - )
```

So an array, in this case, of strings and template calls.

Or here's mixing in `djot` to do the formatting?

```yaml
    narrative: '_cs-author-apa_, cs-issued-year:cs-locators'
```

In fact, with this `djot`:

```markdown
(_cs-author-apa_{.template}, cs-issued-year{.template}: cs-locators{.template})
```

... `djot.js` produces this AST:

```
  para
    str text="("
    emph class="template"
      str text="cs-author-apa"
    str text=", "
    str text="cs-issued-year" class="template"
    str text=": "
    str text="cs-locators" class="template"
    str text=")"
```

So there are tons of options. Maybe there is promise here?

Alas, these examples don't ponder conditionals, in which case it might be better to just use an existing template language like liquid. But then that adds complexity, so ...

PS - I took a look at XSLT 3.0 (`cs:choose` was initially inspired by XSLT 1.0), and they added new conditional support, which is similar to an example I was earlier playing with:

https://www.w3.org/TR/xslt-30/#xsl-choose
